import { Injectable, signal } from '@angular/core';
import { Opening } from '../models/opening.model';
import { POPULAR_OPENING_NAMES } from '../data/popular-openings.const';

/**
 * Loads public/data/chess-openings.json (generated by
 * scripts/generate-chess-openings.mjs from the lichess-org/chess-openings
 * dataset) once and exposes it as signals, plus search/popular helpers.
 */
@Injectable({ providedIn: 'root' })
export class OpeningLibraryService {
  readonly openings = signal<ReadonlyArray<Opening>>([]);
  readonly loaded = signal(false);
  readonly loadError = signal<string | null>(null);

  private loadPromise: Promise<void> | null = null;

  /** Fetch the dataset if it hasn't been loaded yet. Safe to call repeatedly. */
  ensureLoaded(): Promise<void> {
    if (this.loadPromise) return this.loadPromise;

    this.loadPromise = fetch(this.assetPath())
      .then((response) => {
        if (!response.ok) {
          throw new Error(`Failed to load openings dataset: ${response.status}`);
        }
        return response.json() as Promise<Opening[]>;
      })
      .then((openings) => {
        this.openings.set(openings);
        this.loaded.set(true);
      })
      .catch((error) => {
        this.loadError.set(String(error));
        throw error;
      });

    return this.loadPromise;
  }

  /** Case-insensitive substring match against name and ECO code. */
  search(term: string): Opening[] {
    const query = term.trim().toLowerCase();
    if (!query) return [];
    return this.openings().filter(
      (opening) =>
        opening.name.toLowerCase().includes(query) ||
        opening.eco.toLowerCase().includes(query),
    );
  }

  /** Curated shortlist (POPULAR_OPENING_NAMES), in dataset order. */
  popular(): Opening[] {
    const names = new Set(POPULAR_OPENING_NAMES);
    return this.openings().filter((opening) => names.has(opening.name));
  }

  byId(id: string): Opening | undefined {
    return this.openings().find((opening) => opening.id === id);
  }

  private assetPath(): string {
    const baseElement = document.querySelector('base');
    const baseHref = baseElement?.getAttribute('href') || '/';
    const base = baseHref === '/' ? '' : baseHref.replace(/\/$/, '');
    return `${base}/data/chess-openings.json`;
  }
}
