name: CD

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Configure Git user and authentication
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Install dependencies
        run: npm install

      - name: Set release version in Angular environment
        run: |
          sed "s/__RELEASE_VERSION__/${GITHUB_REF#refs/tags\/}/" src/environments/environment.prod.ts.template > src/environments/environment.prod.ts

      - name: Run deployment
        run: npm run deploy
